del ..\fte.lib
cl /nologo /I..\..\include /c agraf.c >> ..\..\msc.out
cl /nologo /I..\..\include /c arg.c >> ..\..\msc.out
cl /nologo /I..\..\include /c aspice.c >> ..\..\msc.out
cl /nologo /I..\..\include /c breakp.c >> ..\..\msc.out
cl /nologo /I..\..\include /c circuits.c >> ..\..\msc.out
cl /nologo /I..\..\include /c clip.c >> ..\..\msc.out
cl /nologo /I..\..\include /c cmath1.c >> ..\..\msc.out
cl /nologo /I..\..\include /c cmath2.c >> ..\..\msc.out
cl /nologo /I..\..\include /c cmath3.c >> ..\..\msc.out
cl /nologo /I..\..\include /c cmath4.c >> ..\..\msc.out
cl /nologo /I..\..\include /c compose.c >> ..\..\msc.out
cl /nologo /I..\..\include /c cpitf.c >> ..\..\msc.out
cl /nologo /I..\..\include /c debugcom.c >> ..\..\msc.out
cl /nologo /I..\..\include /c define.c >> ..\..\msc.out
cl /nologo /I..\..\include /c device.c >> ..\..\msc.out
cl /nologo /I..\..\include /c diff.c >> ..\..\msc.out
cl /nologo /I..\..\include /c display.c >> ..\..\msc.out
cl /nologo /I..\..\include /c doplot.c >> ..\..\msc.out
cl /nologo /I..\..\include /c dotcards.c >> ..\..\msc.out
cl /nologo /I..\..\include /c error.c >> ..\..\msc.out
cl /nologo /I..\..\include /c evaluate.c >> ..\..\msc.out
cl /nologo /I..\..\include /c fourier.c >> ..\..\msc.out
cl /nologo /I..\..\include /c graf.c >> ..\..\msc.out
cl /nologo /I..\..\include /c graphdb.c >> ..\..\msc.out
cl /nologo /I..\..\include /c grid.c >> ..\..\msc.out
cl /nologo /I..\..\include /c inp.c >> ..\..\msc.out
cl /nologo /I..\..\include /c inpcom.c >> ..\..\msc.out
cl /nologo /I..\..\include /c interp.c >> ..\..\msc.out
cl /nologo /I..\..\include /c linear.c >> ..\..\msc.out
cl /nologo /I..\..\include /c mfb.c >> ..\..\msc.out
cl /nologo /I..\..\include /c misccoms.c >> ..\..\msc.out
cl /nologo /I..\..\include /c miscvars.c >> ..\..\msc.out
cl /nologo /I..\..\include /c nutctab.c >> ..\..\msc.out
cl /nologo /I..\..\include /c nutinp.c >> ..\..\msc.out
cl /nologo /I..\..\include /c nutmegif.c >> ..\..\msc.out
cl /nologo /I..\..\include /c options.c >> ..\..\msc.out
cl /nologo /I..\..\include /c outitf.c >> ..\..\msc.out
cl /nologo /I..\..\include /c parse.c >> ..\..\msc.out
cl /nologo /I..\..\include /c plot5.c >> ..\..\msc.out
cl /nologo /I..\..\include /c plotcurv.c >> ..\..\msc.out
cl /nologo /I..\..\include /c points.c >> ..\..\msc.out
cl /nologo /I..\..\include /c postcoms.c >> ..\..\msc.out
cl /nologo /I..\..\include /c postsc.c >> ..\..\msc.out
cl /nologo /I..\..\include /c rawfile.c >> ..\..\msc.out
cl /nologo /I..\..\include /c resource.c >> ..\..\msc.out
cl /nologo /I..\..\include /c runcoms.c >> ..\..\msc.out
cl /nologo /I..\..\include /c shyu.c >> ..\..\msc.out
cl /nologo /I..\..\include /c signal.c >> ..\..\msc.out
cl /nologo /I..\..\include /c spcmdtab.c >> ..\..\msc.out
cl /nologo /I..\..\include /c spiceif.c >> ..\..\msc.out
cl /nologo /I..\..\include /c subckt.c >> ..\..\msc.out
cl /nologo /I..\..\include /c types.c >> ..\..\msc.out
cl /nologo /I..\..\include /c vectors.c >> ..\..\msc.out
cl /nologo /I..\..\include /c where.c >> ..\..\msc.out
cl /nologo /I..\..\include /c x10.c >> ..\..\msc.out
cl /nologo /I..\..\include /c x11.c >> ..\..\msc.out
cl /nologo /I..\..\include /c gens.c >> ..\..\msc.out
cl /nologo /I..\..\include /c newcoms.c >> ..\..\msc.out
cl /nologo /I..\..\include /c dimens.c >> ..\..\msc.out
cl /nologo /I..\..\include /c xgraph.c >> ..\..\msc.out
cl /nologo /I..\..\include /c runcoms2.c >> ..\..\msc.out
cl /nologo /I..\..\include /c breakp2.c >> ..\..\msc.out
lib /OUT:..\fte.lib @response.lib >> ..\..\msc.out
